apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec: 
  type: NodePort
  ports: 
    - port: 3050 
    # port prop 4 pod talk to each other. ex pod A can only connect to pod B at port 3050
      targetPort: 3000 # port in inside pod. ex container port
      nodePort: 31515 # this port 4 expose to browser or other client. random (30000-32767)
  selector: 
    component: web
